# Generated by Django 5.2.17 on 2026-09-10 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration', '0004_event_controls_and_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsite',
            name='accent_color',
            field=models.CharField(default='#BB7D72', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid six-digit HEX color, for example #BB7D72.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='accent_dark_color',
            field=models.CharField(default='#895B52', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid six-digit HEX color, for example #BB7D72.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='brand_symbol',
            field=models.CharField(default='♡', help_text='A short decorative symbol used in the header, hero and footer.', max_length=8),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='countdown_days_label',
            field=models.CharField(default='Days', max_length=24),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='countdown_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='countdown_hours_label',
            field=models.CharField(default='Hours', max_length=24),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='countdown_minutes_label',
            field=models.CharField(default='Minutes', max_length=24),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='countdown_seconds_label',
            field=models.CharField(default='Seconds', max_length=24),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='dark_section_color',
            field=models.CharField(default='#2D2724', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid six-digit HEX color, for example #BB7D72.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='date_card_label',
            field=models.CharField(default='Date & time', max_length=60),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='details_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='details_intro',
            field=models.TextField(default='Everything you need for an effortless arrival and a beautiful evening with us.', max_length=500),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='details_kicker',
            field=models.CharField(blank=True, help_text='Leave empty to use the event title.', max_length=120),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='details_title',
            field=models.CharField(default='Where forever', max_length=120),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='details_title_accent',
            field=models.CharField(default='begins.', max_length=120),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='discover_label',
            field=models.CharField(default='Discover', max_length=40),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='footer_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='footer_left_label',
            field=models.CharField(default='With love', max_length=60),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='footer_note',
            field=models.CharField(default='Thank you for being part of our story.', max_length=240),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='footer_right_label',
            field=models.CharField(default='Forever', max_length=60),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='gallery_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='gallery_intro',
            field=models.TextField(default='A collection of the memories we love most.', max_length=500),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='gallery_kicker',
            field=models.CharField(default='Captured with love', max_length=100),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='gallery_title',
            field=models.CharField(default='Our favorite', max_length=120),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='gallery_title_accent',
            field=models.CharField(default='moments.', max_length=120),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='hero_primary_button_label',
            field=models.CharField(default='Confirm attendance', max_length=70),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='hero_secondary_button_label',
            field=models.CharField(default='View celebration details', max_length=70),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='instagram_label',
            field=models.CharField(default='Instagram', max_length=60),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='intro_skip_label',
            field=models.CharField(default='Skip', max_length=30),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='maps_button_label',
            field=models.CharField(default='Open in Google Maps', max_length=80),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='nav_details_label',
            field=models.CharField(default='Details', max_length=40),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='nav_gallery_label',
            field=models.CharField(default='Moments', max_length=40),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='nav_rsvp_label',
            field=models.CharField(default='RSVP', max_length=40),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='nav_story_label',
            field=models.CharField(default='Our story', max_length=40),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='navigation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='note_card_label',
            field=models.CharField(default='A little note', max_length=60),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='note_card_text',
            field=models.TextField(default='Your presence is the only gift we need. Bring your smile and stay for the memories.', max_length=500),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='note_card_title',
            field=models.CharField(default='Come ready to celebrate', max_length=140),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='page_background_color',
            field=models.CharField(default='#FBF7F2', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid six-digit HEX color, for example #BB7D72.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='quote_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='quote_text',
            field=models.CharField(default='And suddenly, every love song made sense.', max_length=300),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_attendance_label',
            field=models.CharField(default='Will you attend?', max_length=80),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_attending_option',
            field=models.CharField(default='Joyfully attending', max_length=100),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_closed_message',
            field=models.CharField(default='RSVP is currently closed. Thank you for celebrating with us.', max_length=240),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_declining_option',
            field=models.CharField(default='Regretfully declining', max_length=100),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_form_subtitle',
            field=models.CharField(default='Please complete the form below.', max_length=160),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_form_title',
            field=models.CharField(default='RSVP', max_length=60),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_guests_label',
            field=models.CharField(default='Guests', max_length=60),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_intro',
            field=models.TextField(default='We would be delighted to celebrate this chapter with you. Please send your response so we can prepare everything beautifully.', max_length=500),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_kicker',
            field=models.CharField(default='Kindly reply', max_length=80),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_max_guests',
            field=models.PositiveSmallIntegerField(default=8, help_text='Maximum guests allowed in one response (1–20).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_message_label',
            field=models.CharField(default='A message for us', max_length=80),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_message_placeholder',
            field=models.CharField(default='Write a note for the couple…', max_length=160),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_name_label',
            field=models.CharField(default='Your name', max_length=60),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_name_placeholder',
            field=models.CharField(default='Your name', max_length=100),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_optional_label',
            field=models.CharField(default='Optional', max_length=40),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_phone_label',
            field=models.CharField(default='Phone', max_length=60),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_phone_placeholder',
            field=models.CharField(default='+20 ...', max_length=100),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_section_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_submit_label',
            field=models.CharField(default='Send RSVP', max_length=80),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_success_message',
            field=models.CharField(default='Thank you — your RSVP has been received.', max_length=240),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_title',
            field=models.CharField(default='Will you', max_length=120),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='rsvp_title_accent',
            field=models.CharField(default='join us?', max_length=120),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='save_date_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='save_date_kicker',
            field=models.CharField(default='Save the date', max_length=80),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='save_date_title',
            field=models.CharField(default='One beautiful day,', max_length=120),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='save_date_title_accent',
            field=models.CharField(default='one forever.', max_length=120),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Search and social description. Leave empty to use the hero subtitle.', max_length=300),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='site_icon',
            field=models.ImageField(blank=True, help_text='Optional browser icon. A square PNG or WebP works best.', upload_to='branding/icon/'),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='social_share_image',
            field=models.ImageField(blank=True, help_text='Optional image used when the website is shared. Recommended: 1200 × 630 px.', upload_to='branding/social/'),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='soft_background_color',
            field=models.CharField(default='#F3E9E1', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid six-digit HEX color, for example #BB7D72.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='story_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='story_intro',
            field=models.TextField(default='Some chapters begin quietly. Ours became the kind of story we wanted to celebrate with the people we love most.', max_length=500),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='story_kicker',
            field=models.CharField(default='A story worth keeping', max_length=100),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='story_title',
            field=models.CharField(default='Our story', max_length=120),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='text_color',
            field=models.CharField(default='#211C19', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid six-digit HEX color, for example #BB7D72.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='venue_card_label',
            field=models.CharField(default='Venue', max_length=60),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='image_position',
            field=models.CharField(choices=[('center center', 'Center'), ('center top', 'Top'), ('center bottom', 'Bottom'), ('left center', 'Left'), ('right center', 'Right')], default='center center', help_text='Controls which part of the image remains visible when it is cropped.', max_length=20),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='title',
            field=models.CharField(blank=True, help_text='Main title displayed on the photo.', max_length=140),
        ),
        migrations.AddField(
            model_name='storymoment',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventsite',
            name='event_title',
            field=models.CharField(default='Engagement Celebration', help_text='The public celebration title used in the page title and throughout the site.', max_length=160),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='alt_text',
            field=models.CharField(default='Celebration photo', help_text='A short image description for accessibility and search engines.', max_length=180),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='caption',
            field=models.TextField(blank=True, help_text='Optional sentence displayed below the photo title and in the lightbox.', max_length=500),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(help_text='Use a high-resolution JPG, PNG or WebP image.', upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='guests',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='storymoment',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
