# Generated by Django 5.2.17 on 2026-09-10 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration', '0005_eventsite_accent_color_eventsite_accent_dark_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsite',
            name='music_autoplay',
            field=models.BooleanField(default=True, help_text='Try to start music as soon as the website opens. If the browser blocks audible autoplay, an elegant one-tap entry prompt is shown.'),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='music_start_button_label',
            field=models.CharField(default='Enter with music', max_length=60),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='music_start_prompt',
            field=models.CharField(default='Tap to begin the celebration with music', help_text="Shown only when the visitor's browser blocks automatic sound.", max_length=160),
        ),
        migrations.AddField(
            model_name='eventsite',
            name='music_volume',
            field=models.PositiveSmallIntegerField(default=55, help_text='Initial music volume from 0 to 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
