# Generated by Django 5.2.17 on 2026-09-10 21:21

import django.core.validators
from django.db import migrations, models


OLD_PALETTE = {
    "text_color": "#211C19",
    "page_background_color": "#FBF7F2",
    "soft_background_color": "#F3E9E1",
    "accent_color": "#BB7D72",
    "accent_dark_color": "#895B52",
    "dark_section_color": "#2D2724",
}

NEW_PALETTE = {
    "text_color": "#1C211E",
    "page_background_color": "#FBF8F2",
    "soft_background_color": "#EFE7DA",
    "accent_color": "#C29A5B",
    "accent_dark_color": "#8A6330",
    "dark_section_color": "#14231F",
}


def apply_luxury_palette(apps, schema_editor):
    """Upgrade only sites that still use the complete original palette."""
    EventSite = apps.get_model("celebration", "EventSite")
    EventSite.objects.filter(**OLD_PALETTE).update(**NEW_PALETTE)


def restore_original_palette(apps, schema_editor):
    """Reverse only sites that still use the complete upgraded palette."""
    EventSite = apps.get_model("celebration", "EventSite")
    EventSite.objects.filter(**NEW_PALETTE).update(**OLD_PALETTE)


class Migration(migrations.Migration):

    dependencies = [
        ('celebration', '0006_eventsite_music_autoplay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsite',
            name='accent_color',
            field=models.CharField(default='#C29A5B', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid six-digit HEX color, for example #BB7D72.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='eventsite',
            name='accent_dark_color',
            field=models.CharField(default='#8A6330', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid six-digit HEX color, for example #BB7D72.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='eventsite',
            name='dark_section_color',
            field=models.CharField(default='#14231F', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid six-digit HEX color, for example #BB7D72.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='eventsite',
            name='page_background_color',
            field=models.CharField(default='#FBF8F2', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid six-digit HEX color, for example #BB7D72.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='eventsite',
            name='soft_background_color',
            field=models.CharField(default='#EFE7DA', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid six-digit HEX color, for example #BB7D72.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='eventsite',
            name='text_color',
            field=models.CharField(default='#1C211E', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid six-digit HEX color, for example #BB7D72.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.RunPython(apply_luxury_palette, restore_original_palette),
    ]
